# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HAWAI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(553, 389)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Save_btn.setObjectName("Save_btn")
        self.horizontalLayout.addWidget(self.Save_btn)
        self.Open_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Open_btn.setObjectName("Open_btn")
        self.horizontalLayout.addWidget(self.Open_btn)
        self.Change_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Change_btn.setObjectName("Change_btn")
        self.horizontalLayout.addWidget(self.Change_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Save_btn.setText(_translate("MainWindow", "Сохранить"))
        self.Open_btn.setText(_translate("MainWindow", "Открыть"))
        self.Change_btn.setText(_translate("MainWindow", "Изменить"))
